export component MainWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "Electoral Simulator";

    callback open_requested();
    callback save_requested();
    callback import_requested();
    callback quit_requested();

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem { title: @tr("Open"); activated => { root.open_requested(); } }
            MenuItem { title: @tr("Save"); activated => { root.save_requested(); } }
            MenuItem { title: @tr("Import"); activated => { root.import_requested(); } }
            MenuItem { title: @tr("Quit"); activated => { root.quit_requested(); } }
        }
    }

    Text {
        text: "hello world";
        color: green;
    }
}
