import { Button } from "std-widgets.slint";

export struct SlintElection {
    date: string
}

export struct SlintRace {
    id: string
}

export component MainWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "Electoral Simulator";

    // Menubar
    callback new_requested();
    callback open_requested();
    callback save_requested();
    callback import_requested();
    callback quit_requested();

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem { title: @tr("New"); activated => { root.new_requested(); } }
            MenuItem { title: @tr("Open");  activated => { root.open_requested(); } }
            MenuItem { title: @tr("Save"); activated => { root.save_requested(); } }
            MenuItem { title: @tr("Import"); activated => { root.import_requested(); } }
            MenuItem { title: @tr("Quit"); activated => { root.quit_requested(); } }
        }
    }

    // Election Tabs
    in property <[SlintElection]> elections;

    callback select_election(e_num: int);

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 25px;

        HorizontalLayout {
            for election[i] in elections : Rectangle {
                Button {
                    width: parent.width;
                    height: 25px;
                    text: election.date;
                    clicked => { select_election(i); }
                }
            }
        }
    }

    // Race Tabs
    in property <[SlintRace]> races;

    Rectangle {
        x: 0;
        y: 25px;
        width: 15%;

        VerticalLayout {
            for race[i] in races : Rectangle {
                Button {
                    width: parent.width;
                    height: 25px;
                    text: race.id;
                    clicked => { }
                }
            }
        }
    }
}
